webapp/protected/controllers/CarrosController.php
<?php

class CarrosController extends Controller
{
	/**
	* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	* using two-column layout. See 'protected/views/layouts/column2.php'.
	*/
	public $layout='//layouts/column2';


	public $defaultAction = 'index';

	/**
	* @return array action filters
	*/
	public function filters()
	{
		return array(
			//array('application.modules.auth.filters.AuthFilter'),
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	* Specifies the access control rules.
	* This method is used by the 'accessControl' filter.
	* @return array access control rules
	*/
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
				array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	* Displays a particular model.
	* @param integer $id the ID of the model to be displayed
	*/
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	* Creates a new model.
	* If creation is successful, the browser will be redirected to the 'view' page.
	*/
	public function actionCreate()
	{
		$model=new Carro;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Carro']))
		{
			$model->attributes=$_POST['Carro'];
			$model->valor = str_replace('.','',$model->valor);
			$model->valor = str_replace(',','.',$model->valor);
			$model->valor = number_format($model->valor, 2, '.', '');
			$model->valor_parcelado = Functions::jurosComposto($model->valor, Carro::TAXA, $model->parcela->qtd);
			//die($model->valor.' - '.$model->valor_parcelado);
			$model->id_usuario = Yii::app()->user->getId();
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	* Updates a particular model.
	* If update is successful, the browser will be redirected to the 'view' page.
	* @param integer $id the ID of the model to be updated
	*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		$model->valor = number_format($model->valor, 2, ',', '.');
		$model->valor_parcelado = number_format($model->valor_parcelado, 2, ',', '.');
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Carro']))
		{
			$model->attributes=$_POST['Carro'];
			$model->valor = str_replace('.','',$model->valor);
			$model->valor = str_replace(',','.',$model->valor);
			$model->valor = number_format($model->valor, 2, '.', '');
			$model->valor_parcelado = Functions::jurosComposto($model->valor, Carro::TAXA, $model->parcela->qtd);
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	* Deletes a particular model.
	* If deletion is successful, the browser will be redirected to the 'admin' page.
	* @param integer $id the ID of the model to be deleted
	*/
	public function actionDelete($id)
	{
		try
		{
			$this->loadModel($id)->delete();
			if(!isset($_GET['ajax']))
			    Yii::app()->user->setFlash('success','Carro removido com sucesso.');
			else
			    echo '<div class="alert in alert-block fade alert-success"><a data-dismiss="alert" class="close">×</a><strong>Sucesso!</strong> Carro removido com sucesso.</div>';
		}
		catch(CDbException $e)
		{
			if(!isset($_GET['ajax']))
			    Yii::app()->user->setFlash('error','Não foi possível remover este Carro.');
			else
				echo '<div class="alert in alert-block fade alert-error"><a data-dismiss="alert" class="close">×</a><strong>Erro!</strong> Não foi possível remover este Carro.</div>';
		}
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	* Lists all models.
	*/
	public function actionIndex()
	{
		$model=new Carro;
		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	* Manages all models.
	*/
	public function actionAdmin()
	{
		$model=new Carro('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Carro']))
			$model->attributes=$_GET['Carro'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	* Returns the data model based on the primary key given in the GET variable.
	* If the data model is not found, an HTTP exception will be raised.
	* @param integer the ID of the model to be loaded
	*/
	public function loadModel($id)
	{
		$model=Carro::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	* Performs the AJAX validation.
	* @param CModel the model to be validated
	*/
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='carro-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

}

webapp/protected/controllers/MarcasController.php
<?php

class MarcasController extends Controller
{
	/**
	* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	* using two-column layout. See 'protected/views/layouts/column2.php'.
	*/
	public $layout='//layouts/column2';

	/**
	* @return array action filters
	*/
	public function filters()
	{
		return array(
			//array('application.modules.auth.filters.AuthFilter'),
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	* Specifies the access control rules.
	* This method is used by the 'accessControl' filter.
	* @return array access control rules
	*/
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
			'actions'=>array('index','view'),
			'users'=>array('*'),
		),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
			'actions'=>array('create','update'),
			'users'=>array('@'),
		),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
			'actions'=>array('admin','delete'),
			'users'=>array('admin'),
		),
			array('deny',  // deny all users
			'users'=>array('*'),
			),
		);
	}

	/**
	* Displays a particular model.
	* @param integer $id the ID of the model to be displayed
	*/
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	* Creates a new model.
	* If creation is successful, the browser will be redirected to the 'view' page.
	*/
	public function actionCreate()
	{
		$model=new Marca;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Marca']))
		{
			$model->attributes=$_POST['Marca'];
			$model->id_usuario = Yii::app()->user->getId();
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	* Updates a particular model.
	* If update is successful, the browser will be redirected to the 'view' page.
	* @param integer $id the ID of the model to be updated
	*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Marca']))
		{
			$model->attributes=$_POST['Marca'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	* Deletes a particular model.
	* If deletion is successful, the browser will be redirected to the 'admin' page.
	* @param integer $id the ID of the model to be deleted
	*/
	public function actionDelete($id)
	{
		try
		{
			$this->loadModel($id)->delete();
			if(!isset($_GET['ajax']))
			    Yii::app()->user->setFlash('success','Marca removida com sucesso.');
			else
			    echo '<div class="alert in alert-block fade alert-success"><a data-dismiss="alert" class="close">×</a><strong>Sucesso!</strong> Marca removida com sucesso.</div>';
		}
		catch(CDbException $e)
		{
			if(!isset($_GET['ajax']))
			    Yii::app()->user->setFlash('error','Não foi possível remover esta Marca.');
			else
				echo '<div class="alert in alert-block fade alert-error"><a data-dismiss="alert" class="close">×</a><strong>Erro!</strong> Não foi possível remover esta Marca.</div>';
		}
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	* Lists all models.
	*/
	public function actionIndex()
	{
		$model=new Marca;
		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	* Manages all models.
	*/
	public function actionAdmin()
	{
		$model=new Marca('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Marca']))
			$model->attributes=$_GET['Marca'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	* Returns the data model based on the primary key given in the GET variable.
	* If the data model is not found, an HTTP exception will be raised.
	* @param integer the ID of the model to be loaded
	*/
	public function loadModel($id)
	{
		$model=Marca::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	* Performs the AJAX validation.
	* @param CModel the model to be validated
	*/
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='marca-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

webapp/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

webapp/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

webapp/protected/views/layouts/main.php
<!DOCTYPE html>
<html lang="<?php echo Yii::app()->getLanguage(); ?>">
	<head>
		<title>Teste API</title>
		<meta charset="<?php echo Yii::app()->charset; ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <?php
        	define("THEMECSS", Yii::app()->theme->baseUrl . DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR);
        	define("THEMEJS", Yii::app()->theme->baseUrl . DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR);
        	define("THEMEIMG", Yii::app()->theme->baseUrl . DIRECTORY_SEPARATOR . 'img' .DIRECTORY_SEPARATOR);
			define("CORECSS", Yii::app()->baseUrl . DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR);
			define("COREJS", Yii::app()->baseUrl . DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR);
	        Yii::app()->clientScript->registerCSSFile(THEMECSS.'bootstrap.min.css')
	        						->registerCSSFile(THEMECSS.'bootstrap-glyphicons.css');

	        if(!Yii::app()->user->isGuest):
		        Yii::app()->clientScript->registerCSSFile(THEMECSS.'unicorn.main.css')
		        						->registerCSSFile(THEMECSS.'fullcalendar.css')
		        						->registerCSSFile(THEMECSS.'unicorn.grey.css')
		        						->registerCSSFile(CORECSS.'main.css');
		     else:
		     	Yii::app()->clientScript->registerCSSFile(THEMECSS.'unicorn.login.css')
		        						->registerCSSFile(CORECSS.'main.css');
		     endif
        ?>

	</head>
	<body>
		<?php if(!Yii::app()->user->isGuest): ?>
		<div id="header">
			<h1><a href="#"><?php echo CHtml::encode(Yii::app()->name); ?></a></h1>
			<a id="menu-trigger" href="#"><i class="glyphicon glyphicon-align-justify"></i></a>
		</div>
		<div id="user-nav">
            <ul class="btn-group">
            	<li class="btn"><a href="#"><i class="glyphicon glyphicon-user"></i> <span class="text"><?php echo Yii::app()->user->nome; ?></span></a></li>
                <?php if (Yii::app()->user->checkAccess('admin')): ?>
               		<li class="btn"><?php echo CHtml::link('<i class="glyphicon glyphicon-cog"></i> <span class="text">Configuração</span>',array('/site/page','view'=>'config')); ?></li>
            	<?php endif ?>
                <li class="btn"><?php echo CHtml::link('<i class="glyphicon glyphicon-share-alt"></i> <span class="text">Sair</span>',array('/site/logout')); ?></li>
            </ul>
        </div>
        <div id="sidebar">
			<ul>
				<li class="active"><?php echo CHtml::link('<i class="glyphicon glyphicon-home"></i> <span class="text">Dashboard</span>',array('/site/index')); ?></li>
				<li><?php echo CHtml::link('<i class="glyphicon glyphicon-tag"></i> <span class="text">Marcas</span>',array('/marcas/index')); ?></li>
				<li><?php echo CHtml::link('<i class="glyphicon glyphicon-tag"></i> <span class="text">Carros</span>',array('/carros/index')); ?></li>
			</ul>
		</div>
		<?php endif ?>

		<?php echo $content; ?>

		<?php if(!Yii::app()->user->isGuest): ?>
		<div class="row">
			<div id="footer" class="col-12">
			</div>
		</div>
		<?php endif ?>
  		<?php

	        if(!Yii::app()->user->isGuest):
				Yii::app()->clientScript->registerScriptFile(THEMEJS.'excanvas.min.js')
										->registerScriptFile(THEMEJS.'jquery.min.js')
										->registerScriptFile(THEMEJS.'jquery-ui.custom.js')
										->registerCoreScript('jquery')
										->registerScriptFile(THEMEJS.'bootstrap.min.js')
										->registerScriptFile(THEMEJS.'jquery.flot.min.js')
										->registerScriptFile(THEMEJS.'jquery.flot.resize.min.js')
										->registerScriptFile(THEMEJS.'jquery.sparkline.min.js')
										->registerScriptFile(THEMEJS.'fullcalendar.min.js')
										->registerScriptFile(THEMEJS.'jquery.jpanelmenu.min.js')
										->registerScriptFile(THEMEJS.'unicorn.js')
										->registerScriptFile(THEMEJS.'unicorn.dashboard.js')
										->registerScriptFile(COREJS.'jquery.maskMoney.js')
										->registerScriptFile(COREJS.'main.js');
		     else:
					Yii::app()->clientScript->registerScriptFile(THEMEJS.'jquery.min.js')
											->registerCoreScript('jquery')
											->registerScriptFile(THEMEJS.'unicorn.login.js')
											->registerScriptFile(COREJS.'main.js');
		     endif

  		?>
	</body>
</html>